data:
  buffer_size: 16384 #8192
  sampling_rate: 44100
  inp_channels: 1
  out_channels: 1
  train_x_path: /home/yytung/projects/pyneuralfx/frame_work/data/compressor/la2a_snashot/x_train.wav
  train_y_path: /home/yytung/projects/pyneuralfx/frame_work/data/compressor/la2a_snashot/y_train.wav
  valid_x_path: /home/yytung/projects/pyneuralfx/frame_work/data/compressor/la2a_snashot/x_valid.wav
  valid_y_path: /home/yytung/projects/pyneuralfx/frame_work/data/compressor/la2a_snashot/y_valid.wav
  test_x_path: /home/yytung/projects/pyneuralfx/frame_work/data/compressor/la2a_snashot/x_test.wav
  test_y_path: /home/yytung/projects/pyneuralfx/frame_work/data/compressor/la2a_snashot/y_test.wav
model:
  arch: snapshot-gcn
  n_blocks: 9
  kernel_size: 3
  dilation_growth: 2
  n_channels: 16
  causal: True 
loss:
  loss_func: 'hybrid_loss' #esr_trans_loss
  pre_emp: True 
device: cuda
env:
  expdir: exp/transient_awared/snapshot_gcn_trans_v2
  gpu: 0
  gpu_id: 0
  is_jit: False
  debug_mode: True
inference:
  batch_size: 1
train:
  batch_size: 25
  epochs: 500
  interval_log: 10
  interval_ckpt: 450
  interval_val: 450
  lr_patience: 2
  improvement_patience: 6
  lr: 0.001